"""Reusable protocol library for Govee H712-family BLE air purifiers.

The public API intentionally contains no Home Assistant types. Applications may
combine the immutable models and profiles with any BLE transport implementation.
"""

from .framing import FRAME_LENGTH, ProtocolError, build_frame, validate_frame
from .govee_v1 import (
    COMMUNICATION_KEY,
    build_handshake_request,
    decrypt_frame,
    encrypt_frame,
    identify_handshake_frame,
    parse_session_key,
    validate_handshake_confirmation,
)
from .models import (
    DecodedStatus,
    NightLightState,
    PurifierPushUpdate,
    PurifierState,
)
from .profiles import (
    DEFAULT_PROFILE_KEY,
    H7124_PROFILE,
    H7124_PROFILE_KEY,
    MAX_POLLING_INTERVAL_SECONDS,
    MIN_POLLING_INTERVAL_SECONDS,
    MODEL_PROFILE_SCHEMA_PATH,
    PROFILE_DIRECTORY,
    PROFILE_SCHEMA_VERSION,
    PROFILES,
    PROFILES_BY_KEY,
    EncryptionMode,
    ModelProfile,
    ModelSupportStatus,
    NightLightPollingCadence,
    NightLightPollingProfile,
    NightLightPollingRequestOrder,
    NightLightProfile,
    PushNotificationProfile,
    canonicalize_ble_address,
    fan_mode_labels,
    get_profile,
    match_profile,
    model_from_ble_name,
    normalize_ble_address,
    normalize_ble_name,
)
from .protocol import (
    MAX_PM25_UG_M3,
    decode_mode_push,
    decode_night_light_power_brightness,
    decode_night_light_power_brightness_push,
    decode_night_light_rgb_state,
    decode_power_state,
    decode_status,
    is_command_echo,
    is_fan_mode_confirmation,
    is_mode_push,
    is_night_light_brightness_confirmation,
    is_night_light_power_brightness_response,
    is_night_light_power_confirmation,
    is_night_light_rgb_state_response,
    is_power_confirmation,
    is_power_state_response,
    is_status_response,
)

__version__ = "0.1.0"

__all__ = [
    "COMMUNICATION_KEY",
    "DEFAULT_PROFILE_KEY",
    "DecodedStatus",
    "EncryptionMode",
    "FRAME_LENGTH",
    "H7124_PROFILE",
    "H7124_PROFILE_KEY",
    "MAX_PM25_UG_M3",
    "MAX_POLLING_INTERVAL_SECONDS",
    "MIN_POLLING_INTERVAL_SECONDS",
    "MODEL_PROFILE_SCHEMA_PATH",
    "ModelProfile",
    "ModelSupportStatus",
    "NightLightPollingCadence",
    "NightLightPollingProfile",
    "NightLightPollingRequestOrder",
    "NightLightProfile",
    "NightLightState",
    "PROFILE_DIRECTORY",
    "PROFILE_SCHEMA_VERSION",
    "PROFILES",
    "PROFILES_BY_KEY",
    "ProtocolError",
    "PurifierPushUpdate",
    "PurifierState",
    "PushNotificationProfile",
    "__version__",
    "build_frame",
    "build_handshake_request",
    "canonicalize_ble_address",
    "decode_mode_push",
    "decode_night_light_power_brightness",
    "decode_night_light_power_brightness_push",
    "decode_night_light_rgb_state",
    "decode_power_state",
    "decode_status",
    "decrypt_frame",
    "encrypt_frame",
    "fan_mode_labels",
    "get_profile",
    "identify_handshake_frame",
    "is_command_echo",
    "is_fan_mode_confirmation",
    "is_mode_push",
    "is_night_light_brightness_confirmation",
    "is_night_light_power_brightness_response",
    "is_night_light_power_confirmation",
    "is_night_light_rgb_state_response",
    "is_power_confirmation",
    "is_power_state_response",
    "is_status_response",
    "match_profile",
    "model_from_ble_name",
    "normalize_ble_address",
    "normalize_ble_name",
    "parse_session_key",
    "validate_frame",
    "validate_handshake_confirmation",
]
